routes/web.php
<?php

//home
Route::get('/home', '\App\Http\Controllers\HomeController@index')->name('home');;

//login
Route::get('/', '\App\Http\Controllers\Auth\LoginController@showLoginForm')->name('login');
//Route::get('login', '\App\Http\Controllers\Auth\LoginController@showLoginForm')->name('login');
Route::post('/', '\App\Http\Controllers\Auth\LoginController@login');

//logout
Route::post('logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout');

//registration
Route::get('register', '\App\Http\Controllers\Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', '\App\Http\Controllers\Auth\RegisterController@register');

//resetpass
Route::get('password/reset', '\App\Http\Controllers\Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', '\App\Http\Controllers\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', '\App\Http\Controllers\Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', '\App\Http\Controllers\Auth\ResetPasswordController@reset')->name('password.update');

//confirmpass
Route::get('password/confirm', '\App\Http\Controllers\Auth\ConfirmPasswordController@showConfirmForm')->name('password.confirm');
Route::post('password/confirm', '\App\Http\Controllers\Auth\ConfirmPasswordController@confirm');

//emailverify
Route::get('email/verify', '\App\Http\Controllers\Auth\VerificationController@show')->name('verification.notice');
Route::get('email/verify/{id}/{hash}', '\App\Http\Controllers\Auth\VerificationController@verify')->name('verification.verify');
Route::post('email/resend', '\App\Http\Controllers\Auth\VerificationController@resend')->name('verification.resend');


Route::group(['middleware' => ['role:admin']], function () {
    //users
    Route::resource('users', '\App\Http\Controllers\UserController');

    //event calendar
    Route::resource('calendar', '\App\Http\Controllers\EventController');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    // protected $rules = [
    //     'email' => 'sometimes|required|email|unique:users,email,'.$user->id.',id',
    // ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'created_at' => 'datetime: H:m d.m.Y',
        'updated_at' => 'datetime: H:m d.m.Y',
    ];

    public function getNameAttribute($value)
    {
        return strtoupper($value);
    }

    public function setPasswordAttribute($value)
    {   
        $this->attributes['password'] = Hash::make($value);
    }

    public function setNameAttribute($value)
    {
        $this->attributes['name'] = ucfirst(strtolower($value));
    }

    // public function role()
    // {
    //     return $this->hasOne('App\Models\Role', 'role_id', 'user_id');
    // }
    
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Yajra\DataTables\Html\Column;
use Yajra\DataTables\DataTables;
use Illuminate\Http\Request;
use App\DataTables\UserDataTable;
use Yajra\DataTables\Html\Builder; // import class on controller
use App\Models\User;
use App\Models\Role;
use App\Http\Requests\UserRequest;
use App\Http\Requests\UserEditRequest;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rule;
use Illuminate\Validation\Validator;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request, Builder $htmlBuilder)
    {
        if ($request->ajax()) {
            return Datatables::of(User::select(['id', 'name', 'email', 'created_at', 'updated_at']))

            ->addColumn('action', function($user) {
                return view('users.buttons.action', ['user' => $user]);
            } )           
            ->rawColumns(['view', 'edit', 'delete'])
            ->make(true);
        }
        
        $html = $htmlBuilder
            ->addColumn(['data' => 'id', 'name' => 'id', 'title' => 'Номер'])
            ->addColumn(['data' => 'name', 'name' => 'name', 'title' => 'Имя'])
            ->addColumn(['data' => 'email', 'name' => 'email', 'title' => 'Почта'])
            ->addColumn(['data' => 'created_at', 'name' => 'created_at', 'title' => 'Создан'])
            ->addColumn(['data' => 'updated_at', 'name' => 'updated_at', 'title' => 'Обновлен'])
            ->addColumn(['data' => 'action', 'name' => 'action', 'title' => 'Функции']);
        
        $html = $html->parameters([
            'language' => [
                'url' => url('js/langDatatables.json') //localization html-builder
            ],
        ]); 
   
        return view('users.index', compact('html'));
    }
    public function show(User $user, Role $role)
    {   
        return view('users.show', compact('user','role'));
    }
    public function create(User $user)
    {   
        $role = Role::pluck('name','id');
        $roleId = $user->roles->pluck('id');
        return view('users.create', compact('user', 'role', 'roleId'));
    }
    public function store(User $user, UserRequest $request)
    {           
        $user = $user->create($request->all());             
        $user->attachRole($request->role);
        flash(__('flash-messages.create-success'))->success();
        return redirect('users');
    }
    public function edit(User $user)
    {   
        $role = Role::pluck('name','id');
        $roleId = $user->roles->pluck('id');
        return view('users.edit', compact('user', 'role', 'roleId'));
    }
    public function update(User $user, UserEditRequest $editRequest)
    {          
        $editRequestAll = $editRequest->all();
        if(!$editRequestAll['password']) {
            unset($editRequestAll['password']);
        }
        $user->update($editRequestAll);     
        $user->roles()->sync($editRequest->role);         
        flash(__('flash-messages.update-success'))->success();
        return redirect('users');
    }
    public function destroy (User $user) 
    {
        $user->delete($user->id);
        flash(__('flash-messages.del-success'))->success();
        return ['status' => 'success'];
    }
}

resources/views/users/create.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1 class="m-0 text-dark">Создать нового пользователя:</h1>
@stop

@section('content')

  <form action="{{route('users.index')}}" method="POST">
    @csrf
    @method('POST')
    @include('users.form',['submitButton'=>'Добавить'])
  </form>
  <hr/>                   
  <div class="d-flex">
    <div class="p-2">
        <a class="btn btn-info" href="{{route('users.index')}}">Назад</a>
    </div>                                  
  </div>
 
@endsection

resources/views/users/edit.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1 class="m-0 text-dark">Редактировать: {{$user->name}}</h1>
@stop

@section('content')

  <form action="{{route('users.update',$user->id)}}" method="POST"> 
    @csrf
    @method('PATCH')
    @include('users.form',['submitButton'=>'Изменить'])
  </form>

  <hr/>                   
  <div class="d-flex">
    <div class="p-2">
        <a class="btn btn-info" href="{{route('users.index')}}">Назад</a>
    </div>                                 
  </div>
  
@endsection

resources/views/users/form.blade.php
<div class="card card-primary">
  <div class="card-header">
    <h3 class="card-title">Введите данные пользователя</h3>
  </div>
  <form id="quickForm">
    <div class="card-body">
      <div class="form-group">
        <label for="exampleInputName1">
          Имя
        </label>   
        <input type="name" name="name" class="form-control {{ ($errors->has('name')) ? 'is-invalid' : '' }}" id="exampleInputName1" value="{{ old('name') ?? $user->name ?? '' }}" placeholder="Jeff">
          @error('name')
            <div class="badge text-danger">
              {{ $message }}
            </div>
          @enderror      
      </div>  
      <div class="form-group">
        <label for="exampleInputEmail1">
          Почта
        </label>     
        <input type="email" name="email" class="form-control {{ ($errors->has('email')) ? 'is-invalid' : '' }}" id="exampleInputEmail1" value="{{ old('email') ?? $user->email ?? '' }}" placeholder="asd@gmail.com">
          @error('email')
            <div class="badge text-danger">
              {{ $message }}
            </div>
          @enderror 
      </div>              
      <div class="form-group">
        <label for="exampleInputPassword1">
          Пароль
        </label>
        <input type="password" name="password" class="form-control {{ ($errors->has('password')) ? 'is-invalid' : '' }}" id="exampleInputPassword1" value="" placeholder="123456">
          @error('password')
            <div class="badge text-danger">
              {{ $message }}
            </div>
          @enderror         
      </div>  
      <div class="form-group">
        <label for="exampleInputPassword1">
          Роль
        </label>
        <select class="form-control" name="role">
          @foreach ($role as $id => $name)                         
            <option class="input-group p-2 justify-content-center" value="{{$id}}" {{ ($roleId->contains($id)) ? 'selected' : '' }}>
              {{$name}}
            </option>
          @endforeach
        </select>      
      </div>       
    </div>       
    <div class="card-footer">
      <button type="submit" class="btn btn-primary">{{$submitButton}}</button>
    </div>      
  </form>
</div>

  

resources/views/users/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1 class="m-0 text-dark">Пользователи</h1>
@stop

@section('content')
@if (session('status'))
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ session('status') }}
        @include('flash::message')
    </div>                  
@endif

    <div id='del'>
        @include('flash::message')
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <p class="mb-0"> 
                        <div class="input-group">                        
                            <a class="btn btn-primary" href="{{route('users.create')}}">
                                Создать пользователя
                            </a>                         
                        </div>                         
                        <br>
                        {!! $html->table() !!}                   
                    </p>
                </div>
            </div>
        </div>
    </div>
    
@endsection

@section('js')
    <script>
        function removeElementsByClass(className){
            var elements = document.getElementsByClassName(className);
            while(elements.length > 0){
                elements[0].parentNode.removeChild(elements[0]);
            }
        }
        function deleteUser(route, method) {
            $.ajax({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                method: method, // метод HTTP, используемый для запроса
                url: route, // строка, содержащая URL адрес, на который отправляется запрос
                success: function(data) {
                    LaravelDataTables.dataTableBuilder.ajax.reload();
                    let parent = $("#del");
                    let row = document.createElement("div");
                    row.className = "alert alert-success";
                    parent.append(row)
                    row.append("{{__('flash-messages.del-success')}}");
                    $(".alert").fadeTo(2000, 500).slideUp(500, function() {
                        $(".alert").slideUp(500).delay(3000);
                        $('.alert-success').remove();
                        });
                },
                error: function(data) {
                    alert("{{__('flash-messages.del-error')}}");
                },
            });
        }             
    </script>
    {!! $html->scripts() !!}
@endsection

resources/views/users/show.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1 class="m-0 text-dark">Информация: {{$user->name}}</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body"> 
                    <div class="col-md-12">
                        <div class="card card-primary">
                            <div class="card-header">                           
                                <h3 class="card-title">Данные пользователя</h3>
                            </div>
                        </div>    
                        <div class="card-footer">     
                            <div class='d-flex'>                
                                <div>                    
                                    <span>
                                        <b>name:  </b>
                                    </span> 
                                    <span class="p-2 badge-light">
                                        {{$user->name}}
                                    </span>                                                    
                                                      
                                    <span>
                                        <b>email:  </b>
                                    </span>   
                                    <span class="p-2 badge-light">
                                        {{$user->email}}
                                    </span>                                                    
                  
                                    <span>
                                        <b>password:  </b>
                                    </span>   
                                    <span class="p-2 badge-light">
                                        {{$user->password}}
                                    </span>                                                    
                  
                                    <span>
                                        <b>created at:  </b>
                                    </span>   
                                    <span class="p-2 badge-light">
                                        {{$user->created_at}}
                                    </span>                                                    
                   
                                    <span>
                                        <b>updated at:  </b>
                                    </span>   

                                    <span class="p-2 badge-light">
                                        {{$user->updated_at}}
                                    </span>                                                    
                                </div>                               
                            </div>
                        </div>
                        <hr/>                   
                        <div class="d-flex">
                            <div class="p-2">
                                <a class="btn btn-info" href="{{route('users.index')}}">Назад</a>
                            </div>
                            <div class="p-2">
                                <a class="btn btn-warning" href="{{route('users.edit', $user->id)}}">Редактировать</a>     
                            </div>                                  
                        </div>                                                                  
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection



    