routes/web.php
<?php

//home
Route::get('/home', '\App\Http\Controllers\HomeController@index')->name('home');;

//login
Route::get('/', '\App\Http\Controllers\Auth\LoginController@showLoginForm')->name('login');
//Route::get('login', '\App\Http\Controllers\Auth\LoginController@showLoginForm')->name('login');
Route::post('/', '\App\Http\Controllers\Auth\LoginController@login');

//logout
Route::post('logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout');

//registration
Route::get('register', '\App\Http\Controllers\Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', '\App\Http\Controllers\Auth\RegisterController@register');

//resetpass
Route::get('password/reset', '\App\Http\Controllers\Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', '\App\Http\Controllers\Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', '\App\Http\Controllers\Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', '\App\Http\Controllers\Auth\ResetPasswordController@reset')->name('password.update');

//confirmpass
Route::get('password/confirm', '\App\Http\Controllers\Auth\ConfirmPasswordController@showConfirmForm')->name('password.confirm');
Route::post('password/confirm', '\App\Http\Controllers\Auth\ConfirmPasswordController@confirm');

//emailverify
Route::get('email/verify', '\App\Http\Controllers\Auth\VerificationController@show')->name('verification.notice');
Route::get('email/verify/{id}/{hash}', '\App\Http\Controllers\Auth\VerificationController@verify')->name('verification.verify');
Route::post('email/resend', '\App\Http\Controllers\Auth\VerificationController@resend')->name('verification.resend');


Route::group(['middleware' => ['role:admin']], function () {
    //users
    Route::resource('users', '\App\Http\Controllers\UserController');

    //event calendar
    Route::resource('calendar', '\App\Http\Controllers\EventController');
});

resources/views/calendar/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
    <h1 class="m-0 text-dark">Календарь</h1>
@stop

@section('css')
    <link href="{{ asset('fullcalendar/lib/main.css') }}" rel='stylesheet' />
    <!-- <link href='https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.css' rel='stylesheet' /> -->
    <link href='https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.1/css/all.css' rel='stylesheet'>
@stop

@section('content')



    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <p class="mb-0">   
                    <div class="input-group">  
                        <a class="btn btn-primary" href="{{route('users.create')}}">
                            Создать событие
                        </a>                       
                    </div>  
                    <hr/>
                    <div id='calendar'></div>         
                                                                                      
                </p>
            </div>
        </div>
    </div>


@endsection

@section('js')

{{-- FullCalendar --}}

    <script src="{{ asset('fullcalendar/lib/main.js') }}"></script>
    <script src="{{ asset('fullcalendar/lib/locales-all.js') }}"></script>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        var calendarEl = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarEl, {
            themeSystem: 'bootstrap'
        });       
        calendar.render();
        calendar.setOption('height', 700);
        calendar.setOption('contentHeight', 650);
        calendar.setOption('locale', 'ru');
      });
    </script>

@stop